export const FETCH_PICTURE_LIST_START = 'FETCH_PICTURE_LIST_START';
export const FETCH_PICTURE_LIST_SUCCESS = 'FETCH_PICTURE_LIST_SUCCESS';
export const FETCH_PICTURE_LIST_ERROR = 'FETCH_PICTURE_LIST_ERROR';

export const FETCH_SINGLE_PICTURE_START = 'FETCH_SINGLE_PICTURE_START';
export const FETCH_SINGLE_PICTURE_SUCCESS = 'FETCH_SINGLE_PICTURE_SUCCESS';
export const FETCH_SINGLE_PICTURE_ERROR = 'FETCH_SINGLE_PICTURE_ERROR';

export const SEARCH_PICTURE_START = 'SEARCH_PICTURE_START';
export const SEARCH_PICTURE_SUCCESS = 'SEARCH_PICTURE_SUCCESS';
export const SEARCH_PICTURE_ERROR = 'SEARCH_PICTURE_ERROR';
